# Generated by Django 3.2.7 on 2021-10-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('length', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collars', to='main_app.dog')),
            ],
        ),
    ]
